### ISSUE TITLE
Request for Help with Usage

### ISSUE THREAD

**Issue by DavidBerdik** [andrew892/mf_bruteforce_nonce#1]
Hello,

I am relatively new to experimenting with NFC and would appreciate a brief explanation of how to use this. Does it interface with a proxmark for reading a card?

Thanks!

**Comment by andrew892** [comment]
Hi,

this tool is for recovering (partial or entire) key from nested authentication in Mifare Classic sniffed traces. So, you have to read an authentication trace with some sniffer (e.g. proxmark) and then you can launch this tool.

**Comment by DavidBerdik** [comment]
This is what I needed to know. Thanks @andrew892!
